#!/bin/bash

# Please make sure you opened vscodium at least once to generate the right files.

curl -sSL https://codeberg.org/h8d13/ZUNO/raw/branch/master/asapsh | sudo bash

rm -f /home/$USER/.vscode-oss/extensions/extensions.json

# Then open it again. Extension should now work try to paste a block of code. 
