#!/bin/bash
export U_HOME="$HOME"
export C_HOME="$U_HOME/.config/"
export L_HOME="$U_HOME/.local/"

export FIREFOX_DIR="/usr/lib/firefox"
export DIST_DIR="$FIREFOX_DIR/distribution"
export EXTENSIONS_DIR="$DIST_DIR/extensions"